#!/bin/bash

# Author: Sean Fisk <sean@seanfisk.com>
# URL: https://github.com/seanfisk/cmake-flymake
#
# Copyright (C) 2011 by Sean Fisk <sean@seanfisk.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# removeMakefiles.sh by Nil Geisweiller
#
# That script remove recursively all Makefile.flymake
# (or rather Makefile for now) from the CMake project.

#MAKEFILE_NAME="Makefile.flymake"
MAKEFILE_NAME="Makefile"

# For each CMakeLists.txt found from the current directory and descendants
# it removes the associated Makefile.flymake (or rather Makefile for now).
while read -r -d $'\0' FILEPATH
do
    RELATIVE_MAKEFILE_DIR=${FILEPATH%/*}
    rm "${RELATIVE_MAKEFILE_DIR}/${MAKEFILE_NAME}"
done < <( find . -name "CMakeLists.txt" -print0 )